TRAINED = "TRAINED"
EVALUATED = "EVALUATED"
PROMOTION_APPROVED = "PROMOTION_APPROVED"
PROMOTED_HML = "PROMOTED_HML"
PROMOTED_PRD = "PROMOTED_PRD"
DEPLOYED_HML = "DEPLOYED_HML"
DEPLOYED_PRD = "DEPLOYED_PRD"
ROLLED_BACK = "ROLLED_BACK"

VALID_MODEL_STATES = {
    TRAINED,
    EVALUATED,
    PROMOTION_APPROVED,
    PROMOTED_HML,
    PROMOTED_PRD,
    DEPLOYED_HML,
    DEPLOYED_PRD,
    ROLLED_BACK,
}

ARTIFACT_VALID_STATES = {
    TRAINED,
    EVALUATED,
    PROMOTION_APPROVED,
    PROMOTED_HML,
    PROMOTED_PRD,
    DEPLOYED_HML,
    DEPLOYED_PRD,
    ROLLED_BACK,
}
