active_provider: github_actions

providers:
  github_actions:
    enabled: true
    deploy_enabled: true
    rehearsal_required_for_hml: true
    rehearsal_required_for_prd: true

  azure_devops:
    enabled: false
    deploy_enabled: false
    rehearsal_required_for_hml: true
    rehearsal_required_for_prd: true

  bitbucket:
    enabled: false
    deploy_enabled: false
    rehearsal_required_for_hml: true
    rehearsal_required_for_prd: true
