providers:
  github_actions:
    dev:
      required:
        - DEV_WORKSPACE_HOST
        - DEV_DATABRICKS_TOKEN
        - DEV_DEPLOY_USER
    hml:
      required:
        - HML_WORKSPACE_HOST
        - HML_DATABRICKS_TOKEN
        - HML_DEPLOY_USER
    prd:
      required:
        - PRD_WORKSPACE_HOST
        - PRD_DATABRICKS_TOKEN
        - PRD_DEPLOY_USER

  azure_devops:
    dev:
      required:
        - DEV_WORKSPACE_HOST
        - DEV_DATABRICKS_TOKEN
        - DEV_DEPLOY_USER
    hml:
      required:
        - HML_WORKSPACE_HOST
        - HML_DATABRICKS_TOKEN
        - HML_DEPLOY_USER
    prd:
      required:
        - PRD_WORKSPACE_HOST
        - PRD_DATABRICKS_TOKEN
        - PRD_DEPLOY_USER

  bitbucket:
    dev:
      required:
        - DEV_WORKSPACE_HOST
        - DEV_DATABRICKS_TOKEN
        - DEV_DEPLOY_USER
    hml:
      required:
        - HML_WORKSPACE_HOST
        - HML_DATABRICKS_TOKEN
        - HML_DEPLOY_USER
    prd:
      required:
        - PRD_WORKSPACE_HOST
        - PRD_DATABRICKS_TOKEN
        - PRD_DEPLOY_USER

  aws:
    dev:
      required:
        - DEV_WORKSPACE_HOST
        - DEV_DATABRICKS_TOKEN
        - DEV_DEPLOY_USER
    hml:
      required:
        - HML_WORKSPACE_HOST
        - HML_DATABRICKS_TOKEN
        - HML_DEPLOY_USER
    prd:
      required:
        - PRD_WORKSPACE_HOST
        - PRD_DATABRICKS_TOKEN
        - PRD_DEPLOY_USER
