providers:
  github_actions:
    dev:
      required:
        - DEV_WORKSPACE_HOST
        - DEV_DATABRICKS_TOKEN
        - DEV_COMPUTE_MODE
    hml:
      required:
        - HML_WORKSPACE_HOST
        - HML_DATABRICKS_TOKEN
        - HML_COMPUTE_MODE
    prd:
      required:
        - PRD_WORKSPACE_HOST
        - PRD_DATABRICKS_TOKEN
        - PRD_COMPUTE_MODE

  azure_devops:
    dev:
      required:
        - DEV_WORKSPACE_HOST
        - DEV_DATABRICKS_TOKEN
        - DEV_COMPUTE_MODE
    hml:
      required:
        - HML_WORKSPACE_HOST
        - HML_DATABRICKS_TOKEN
        - HML_COMPUTE_MODE
    prd:
      required:
        - PRD_WORKSPACE_HOST
        - PRD_DATABRICKS_TOKEN
        - PRD_COMPUTE_MODE

  bitbucket:
    dev:
      required:
        - DEV_WORKSPACE_HOST
        - DEV_DATABRICKS_TOKEN
        - DEV_COMPUTE_MODE
    hml:
      required:
        - HML_WORKSPACE_HOST
        - HML_DATABRICKS_TOKEN
        - HML_COMPUTE_MODE
    prd:
      required:
        - PRD_WORKSPACE_HOST
        - PRD_DATABRICKS_TOKEN
        - PRD_COMPUTE_MODE

  aws:
    dev:
      required:
        - DEV_WORKSPACE_HOST
        - DEV_DATABRICKS_TOKEN
        - DEV_COMPUTE_MODE
    hml:
      required:
        - HML_WORKSPACE_HOST
        - HML_DATABRICKS_TOKEN
        - HML_COMPUTE_MODE
    prd:
      required:
        - PRD_WORKSPACE_HOST
        - PRD_DATABRICKS_TOKEN
        - PRD_COMPUTE_MODE
