version: 1
targets:
  dev:
    mode: development
    workspace:
      root_path: /Workspace/Users/${workspace.current_user.userName}/.bundle/b3_databricks_platform/dev
    run_as:
      type: user_name
      value: CURRENT_USER
    deploy_user_mode: current_user
    catalogs:
      default: b3_dev
      ai: b3_dev
    schemas:
      default: default
      ai: ai
    volumes:
      artifacts: TO_BE_DEFINED
      checkpoints: TO_BE_DEFINED
    secret_scopes:
      default: TO_BE_DEFINED
      serving: TO_BE_DEFINED
    groups:
      readers:
      - TO_BE_DEFINED
      operators:
      - TO_BE_DEFINED
      admins:
      - TO_BE_DEFINED
    cluster_policies:
      default: TO_BE_DEFINED
      jobs: TO_BE_DEFINED
    service_principals:
      deploy: TO_BE_DEFINED
      run_as: TO_BE_DEFINED
  hml:
    mode: production
    workspace:
      root_path: /Workspace/Shared/.bundle/b3_databricks_platform/hml
    run_as:
      type: service_principal_name
      value: TO_BE_DEFINED
    deploy_user_mode: explicit
    catalogs:
      default: b3_hml
      ai: b3_hml
    schemas:
      default: default
      ai: ai
    volumes:
      artifacts: TO_BE_DEFINED
      checkpoints: TO_BE_DEFINED
    secret_scopes:
      default: TO_BE_DEFINED
      serving: TO_BE_DEFINED
    groups:
      readers:
      - TO_BE_DEFINED
      operators:
      - TO_BE_DEFINED
      admins:
      - TO_BE_DEFINED
    cluster_policies:
      default: TO_BE_DEFINED
      jobs: TO_BE_DEFINED
    service_principals:
      deploy: TO_BE_DEFINED
      run_as: TO_BE_DEFINED
  prd:
    mode: production
    workspace:
      root_path: /Workspace/Shared/.bundle/b3_databricks_platform/prd
    run_as:
      type: service_principal_name
      value: TO_BE_DEFINED
    deploy_user_mode: explicit
    catalogs:
      default: b3_prd
      ai: b3_prd
    schemas:
      default: default
      ai: ai
    volumes:
      artifacts: TO_BE_DEFINED
      checkpoints: TO_BE_DEFINED
    secret_scopes:
      default: TO_BE_DEFINED
      serving: TO_BE_DEFINED
    groups:
      readers:
      - TO_BE_DEFINED
      operators:
      - TO_BE_DEFINED
      admins:
      - TO_BE_DEFINED
    cluster_policies:
      default: TO_BE_DEFINED
      jobs: TO_BE_DEFINED
    service_principals:
      deploy: TO_BE_DEFINED
      run_as: TO_BE_DEFINED
