version: 1

defaults:
  mode: auto
  classic:
    spark_version: "15.4.x-scala2.12"
    node_type_id: "i3.xlarge"
    driver_node_type_id: "i3.xlarge"
    num_workers: 0
  serverless:
    environment_key: "default"
    environment_version: "2"

targets:
  dev:
    mode: auto

  hml:
    mode: auto

  prd:
    mode: auto
