documents:
- document_id: c_g_jung_o_homem_e_seus_simbolos
  display_name: C G Jung O Homem e seus Simbolos
  source_file_name: C_G_Jung_O_Homem_e_seus_Simbolos.pdf
  aliases:
  - c g jung o homem e seus simbolos
  - c g jung o homem e seus simbolos
- document_id: o_homem_a_descoberta_da_sua_alma_c_g_jung
  display_name: O HOMEM À DESCOBERTA DA SUA ALMA C. G. Jung
  source_file_name: O HOMEM À DESCOBERTA DA SUA ALMA - C. G. Jung.pdf
  aliases:
  - o homem a descoberta da sua alma c. g. jung
  - o homem a descoberta da sua alma c. g. jung
- document_id: os_arquetipos_e_o_inconsciente_coletivo_c_g_jung
  display_name: Os arquétipos e o inconsciente coletivo C G Jung
  source_file_name: Os arquétipos e o inconsciente coletivo - C G Jung.pdf
  aliases:
  - os arquetipos e o inconsciente coletivo c g jung
  - os arquetipos e o inconsciente coletivo c g jung
- document_id: o_livro_vermelho_c_g_jung
  display_name: o livro vermelho c g jung
  source_file_name: o-livro-vermelho-c-g-jung.pdf
  aliases:
  - o livro vermelho c g jung
  - o livro vermelho c g jung
